### PR TITLE
add config for insuedthueringen.de

### PR DESCRIPTION
**Pull request by Strubbl**

### CODE REVIEW

**Comment by HolgerAusB** [comment]
@Strubbl, you are an experienced contributor and I am relatively new here. But on my test environment I see no difference between your config and no config.  Are you using this on wallabag or with Fulltext-RSS (FTR)?

This one works for me on FTR 3.9.13, no cache at all

```
body: //div[@class='brickgroup restricted-area']
author: //a[@itemprop='author']
title: //span[@class='article-headline']

strip: //div[@data-upscore-zone="Artikel Headline"]
strip: //div[contains(@data-b-title, 'Sharing Button')]

strip_id_or_class: 'badges'
strip_id_or_class: 'read-more'
strip_id_or_class: 'paywal'
strip_id_or_class: 'rsCaption'
strip_id_or_class: 'gallery-count'

replace_string(<a class="rsImg" href=): <img class="rsImg" src=

prune: no

test_url: https://www.insuedthueringen.de/inhalt.weltfahrradtag-wie-gut-laesst-sich-suhl-mit-dem-fahrrad-erkunden.222e08c6-76f1-48b4-a695-47b5ffe59724.html
test_url: https://www.insuedthueringen.de/inhalt.schulstaffellauf-540-mal-den-steinweg-hoch-und-runter.271d5394-7da5-4dfd-92d0-409abd20674c.html
```

**Comment by Strubbl** [comment]
Hi Holger, i am using wallabag. Without this config i also get the content, but also all the content your stripping off - especially the boxes from the sidebar. I cannot test with your second URL, because it requires an account.

**Comment by Strubbl** [comment]
I just tested your config. It looks better on the weltfahrradtag article, because the title image is included. If i use it for https://www.insuedthueringen.de/inhalt.sos-festival-in-suhl-hilfe-die-1980er-kommen-zurueck.b59803b8-b2f2-4c03-9dfd-0c7afc80faae.html, i also see the paragraphs with "Unsere Empfehlung für Sie", which i would strip. I like, that the figures are kept.

**Comment by Strubbl** [comment]
This website is really hard to configure, because every article is different. I tried to include images, but had to give up. I'll keep my config only text-focussed for now.

**Comment by HolgerAusB** [comment]
@Strubbl: Yes this side is crazy. The 1980er article has 130 pictures in the galery. With the second link, I wanted to show, that I cleared the paywall-ad. That article is free today, btw.

The following config shows ALL galery pics in Wallabag and FTR
but
not the single article-image on shorter articles :-( for Wallabag (FTR is fine as well here)
Maybe you can find a hint with that:

```
body: //div[contains(concat(' ',normalize-space(@class),' '),' item ')]/p | //img[@id='article-image'] | //div[@class='brickgroup restricted-area']
author: //a[@itemprop='author']

strip: //div[contains(@data-b-title, 'Sharing Button')]

strip_id_or_class: 'badges'
strip_id_or_class: 'read-more'
strip_id_or_class: 'paywall'
strip_id_or_class: 'mod-paywall'
strip_id_or_class: 'rsCaption'
strip_id_or_class: 'gallery-count'
strip_id_or_class: 'articleTeaser'
strip_id_or_class: 'article-header'

replace_string(data-src=): src=
replace_string( - inSüdthüringen):
```

I also striped the title suffix " - inSüdthürungen"

**Comment by HolgerAusB** [comment]
In Fulltext-RSS it passes all my test-urls but NOT in Wallabag. In the short articles the domain-part is striped from the image-path, so only a broken-image-symbol is shown.

https://www.insuedthueringen.de/inhalt.thueringer-theater-ueber-tote-pferde-und-fromme-wuensche.7c7aca95-8c03-48c7-999f-5693e0c3f743.html
https://www.insuedthueringen.de/inhalt.weltfahrradtag-wie-gut-laesst-sich-suhl-mit-dem-fahrrad-erkunden.222e08c6-76f1-48b4-a695-47b5ffe59724.html

image

After removing your `strip: //noscript` everything works fine in Fulltext-RSS and Wallabag 2.5.3

**Comment by Strubbl** [comment]
This is strange. I can see both title images of the links you provided with that config in wallabag. Which wallabag version are you using? 
I introduced the noscript stripping because otherwise a low resolution image is being used.

**Comment by Strubbl** [comment]
Sorry, i overlooked this. I use 2.5.4. Unfortunately my wallabag.it account is not active anymore, so that i can double-check this.

**Comment by HolgerAusB** [comment]
I can't find that setting in UI or in the files. The image is shown in the article-list view of wallabag but not in article view

**Comment by Strubbl** [comment]
It is below the path /settings#set-misc and there it is the most bottom option, which i set to 1

**Comment by Strubbl** [comment]
Yes, that made a difference, because local image caching in wallabag understands lazy loading of images, but the usual web view does not. The latest change shall make the config work for you, too. Or?

**Comment by HolgerAusB** [comment]
Arrrrrr, I dont use my wallabag admin for collecting, so I havent found it. Setting is 0. will try it now,

Meanwhile could you try:
```
#strip: //noscript
replace_string(.normalized.jpg): .original1024.jpg
```

**Comment by HolgerAusB** [comment]
OK, missed your last commit. This works with Wallabag cache=0 and with FTR:

`replace_string(srcset=): notneeded=`

Do you still need your `strip: //noscript` then? I don't see any difference after masking srcset

**Comment by Strubbl** [comment]
Thanks a lot for testing. I removed the noscript stripping. I think we are finished with this config for now.

**Comment by HolgerAusB** [comment]
@j0k3r please prove and merge

**Comment by j0k3r** [comment]
Good job guys!

**Pull request merged**
