### PR TITLE
add config for photografix-magazin.de

### PR DESCRIPTION
**Pull request by Strubbl**

### CODE REVIEW

**Comment by HolgerAusB** [comment]
@Strubbl `test_url:` line is missing, please add it. I could not find a multipage-article. If you have the link please, so I could check, if that works with wallabag and FTR

**Comment by Strubbl** [comment]
Thanks for the feedback. There could also be some improvements made for nicer reading. But i did not find the time to strip, e.g. the pagination elements. If you want me to do this, please leave this open. I try to find some time in the next days to work on this.

**Comment by HolgerAusB** [comment]
I will remove the pagination links from content in a minute

**Comment by Strubbl** [comment]
thank you

**Pull request merged**
