### PR TITLE
Update canardpc.com.txt

### PR DESCRIPTION
**Pull request by Simounet**
Have a nice day.

### CODE REVIEW

**Comment by HolgerAusB** [comment]
Thank you @Simounet, are you really sure, you want to have both strip lines?
```
strip: //div[contains(@class, "post-row desktop")]
strip: //div[contains(@class, "post-row mobile")]
```
You will loose e.g. 7 screenshots from https://www.canardpc.com/jeu-video/dossier-jeu-video/comment-lucasarts-a-invente-le-pointnclick-2/

I would try to keep desktop and strip some text fringe from that node

**Comment by Simounet** [comment]
I saw that the screenshots used in the right sidebar were already displayed into the bottom slideshow.

**Comment by HolgerAusB** [comment]
@Simounet I do not have a slideshow. Not on original webpage and not in the wallabag excerpt (using your PR version of config). I only have the two in-article images then.
Might that be a subscriber feature?

**Comment by Simounet** [comment]
Yes, it is. I think you can't test this config without the paywall being enabled.

**Comment by HolgerAusB** [comment]
so I would like to kepp the "post-row desktop" in. You may enable the strip in your server again, using a different 'custom' config folder. You just found my wiki article ;-) and you can also use this for custom configs.

**Comment by Simounet** [comment]
I just checked, and the slideshow is gone. But if we let the "post-row desktop", we've got a lot of screenshots before the content, that is a bummer. The perfect solution would be to put it at the end (like in the previous version of the site). I'll try to do it, but if you have a better idea, I'm all ears. 😅

**Comment by HolgerAusB** [comment]
In some of the config files there is an interesting keyword:
`move_into([XPath]): [XPath]`

But I think that isn't implemented in FTR and graby, or @fivefilters, @j0k3r?

Or maybe I used in wrong in my  short tests:
`move_into(footer): //div[@class='post-row desktop']` while //footer has to be concatenate to the body

**Pull request merged**
