### PR TITLE
Two scene release announcement sites

### PR DESCRIPTION
**Pull request by paour**

### CODE REVIEW

**Comment by fivefilters** [comment]
Thanks. Is there a mistake in the strip directives? Not sure what the //p[strong="Links:"] and the other one is supposed to mean. <p> elements with <strong>Links:...</strong> inside? or something else?

**Comment by paour** [comment]
That was the intention, yes. Is that not correct?

**Comment by fivefilters** [comment]
I looked for "Links:" and "Download:" after opening the test URL but couldn't see them, so that's why I asked.

But if the intention is to strip `p` elements which contains `<strong>Links: ...</strong>` (where ... is some other text within the `strong` element) you'll have to use XPath like the following:

    //p[contains(strong, "Links:")]`

If it contains a strong element with only the string "Links:" then your XPath should work fine. If it looks okay, let me know and I'll merge it.

**Comment by paour** [comment]
Thanks for the help @fivefilters, my xpath is rusty indeed :-)

I've removed that file entirely. I had not realized it, but the site is defunct.

**Comment by fivefilters** [comment]
Great, thanks! :)

**Pull request merged**
