### PR TITLE
Create dailynord.fr.txt

### PR DESCRIPTION
**Pull request by elibadou384**

### CODE REVIEW

**Comment by fivefilters** [comment]
Not a fan of body selectors which focus only on paragraph elements:

    //section[@id='pagearticle']/p

They leave out things like headings (h1-h6), lists (li/ul), block quotes (blockquote), etc. Is it necessary here?

**Comment by elibadou384** [comment]
Thanks a lot for your feedback !
You are right, the /p selector is probably too restrictive.
I used it (in the tested url) to get rid of the text at the end of the article talking about "moderating comments".
I'll try to come back with a better solution.

**Comment by fivefilters** [comment]
Thanks. We had a report recently were a user said their article didn't contain any of the bullet points which appeared in the original. It turned out the site config file had a section intended to remove advertising but with a rule that stripped all list items `<li>` elements. So I'm trying to be a little more vigilant with things that might cause problems later. :)

**Comment by elibadou384** [comment]
I understand. I've removed the /p selector ind find the way to remove everything including text that follow the "comments" section. Don't hesitate to tell me if you think it is still problematic.
Thanks.

**Pull request merged**
