### PR TITLE
Medium.com

### PR DESCRIPTION
**Pull request by HolgerAusB**
as requested by @fivefilters at https://github.com/wallabag/wallabag/issues/6711

### CODE REVIEW

**Comment by fivefilters** [comment]
Many thanks @HolgerAusB 🙏

**Comment by fivefilters** [comment]
@HolgerAusB Just curious, shouldn't medium.com.txt not be updated too?

**Comment by HolgerAusB** [comment]
@fivefilters I think so, but I haven't tested that too much. I don't know if I'll find the time till next week Tuesday to do so. Feel free to copy that. if you want

**Comment by fivefilters** [comment]
@HolgerAusB Understood! I tested it myself yesterday and it worked okay, but I'll test a bit more and then copy contents over if it looks good. Thanks again.

**Comment by fivefilters** [comment]
@HolgerAusB Quick note to say I copied your changes to .medium.com.txt too. The results were much better than the current one in my tests (especially when client-side rendered HTML was processed, e.g. via Push to Kindle) . Thanks again! 👍  https://github.com/fivefilters/ftr-site-config/commit/a620a5e1d0c253e25207df47b3f612eb5b4a121c

**Pull request merged**
