### PR TITLE
add few websites

### PR DESCRIPTION
**Pull request by bil-elmoussaoui**

### CODE REVIEW

**Comment by fivefilters** [comment]
Hi there. Many thanks for these, but extensions should be .txt. Are you able to resubmit? If not we'll fix it this end. Thank you.

**Comment by bil-elmoussaoui** [comment]
Fixed!

**Comment by bil-elmoussaoui** [comment]
Any news?

**Comment by fivefilters** [comment]
Sorry, I thought I already merged this after your update. Thanks so much! :)

**Comment by bil-elmoussaoui** [comment]
Not a problem :)

**Pull request merged**
