### PR TITLE
Create alternatives-economiques.fr

### PR DESCRIPTION
**Pull request by biva**
What is working? 
- Title: OK
- Date: OK
- Author: OK
- Remove footer : OK

What is not working?
- Body: an additional word is included at the beginning ("école" in the example). It corresponds to the topic of the articles. It shouldn't be fetched
- Images/Graphs are not fetched: There are blocks `div.c-bloc-medias__inner` but I don't know how to grab them.
- Quotes are fetched. There's a block 'div.c-epigraph.o-page__block--offset.u-thema' but I don't know how to remove it. I'd like to remove them in the same way as it had been done in abonnes.lemonde.fr:
`strip_id_or_class: accroche
strip_id_or_class: encart`
- Paywall: commented out because it's not working yet

Initial pull request here: https://github.com/j0k3r/graby-site-config/pull/24

### CODE REVIEW

**Comment by biva** [comment]
Hello, any update on this one? I'm having issues with:
- initial word in the body
- images/graphs
- quotes
Could somebody help? @j0k3r ? Example used: https://www.alternatives-economiques.fr/reforme-rythmes-scolaires-grand-malentendu/00080361

**Comment by biva** [comment]
In addition, I'd love to see this site working with wallabag and paywall. I started to work on it, but I'm not skilled enough (see https://github.com/j0k3r/graby-site-config/pull/24)

@j0k3r : what should I do? Keep this PR here for the parsing only, and open a new issue in https://github.com/j0k3r/graby-site-config ? Or gather everything in one single issue/PR in https://github.com/j0k3r/graby-site-config ?

**Comment by biva** [comment]
Great, thanks @j0k3r 
I now have a subscription to the website in order to test the paywall: do you want the credentials to test it?

**Comment by biva** [comment]
Just a few remarks on your config file, tested with https://www.alternatives-economiques.fr/etats-unis-overdoses-tuent-plus-armes-a-feu/00085167 : 
- The standard parser retrieves the graph, while your config doesn't
- The standard parser retrieves the note ("1. « The President’s Commission on Combating Drug Addiction and the Opioid Crisis », 1er novembre 2017, https://lc.cx/Wd2z") while your config doesn't
- The title is not printed out
- The quotes are still fetched. There's a block 'div.c-epigraph.o-page__block--offset.u-thema' but I don't know how to remove it. I'd like to remove them in the same way as it had been done in abonnes.lemonde.fr: `strip_id_or_class: accroche` and `strip_id_or_class: encart`
- Could we also remove the "A lire Alternatives Economiques n°379 - 05/2018" in the block `article.c-kiosk--single` (in detail: `//article[contains(concat(' ',normalize-space(@class),' '),' c-kiosk--single ')]`
- Could we also remove the "Santé +2 Articles" in the block `//div[contains(concat(' ',normalize-space(@class),' '),' c-same-subject ')]`
- I can't see the log with your config

I tried to improve it with these lines, but it doesn't work:
- strip: //div[contains(concat(' ',normalize-space(@class),' '),' c-same-subject ')]
- strip: //article[contains(concat(' ',normalize-space(@class),' '),' c-kiosk--single ')]
- strip_id_or_class: c-same-subject
- strip_id_or_class: c-kiosk--single

**Comment by biva** [comment]
For the paywall, should we continue to discuss it here, or should we reopen https://github.com/j0k3r/graby-site-config/pull/24 or should I create a new issue in https://github.com/j0k3r/graby-site-config ?

**Comment by biva** [comment]
Hello @j0k3r : what do you think about my last amendment? Is it satisfying? Could we merge it?

**Comment by fivefilters** [comment]
Thank you! 👍

**Pull request merged**
