### PR TITLE
Adding "Le Monde Diplomatique" config file

### PR DESCRIPTION
**Pull request by Linuxine**

### CODE REVIEW

**Comment by Simounet** [comment]
Hi there,
First of all, thanks for your submission.
I think there is an unwanted merge here (Merge pull request #1 from Linuxine/Le-monde-diplo). The `test_url` is missing. You can fill it with the URL you tested it on wallabag.

**Comment by Simounet** [comment]
Why did you closed this ? You can do a `git push --force-with-lease`.

**Comment by Simounet** [comment]
👍

**Comment by fivefilters** [comment]
Thank you! I noticed that some links lead to blog.mondediplo.net and some to monde-diplomatique.fr. If both these have the same HTML structure, you can copy the site config file `monde-diplomatique.fr.txt` and save a copy as `blog.mondediplo.net.txt`

**Pull request merged**
