### PR TITLE
servethehome and lowtechmagazine

### PR DESCRIPTION
**Pull request by TheOneValen**
Selected content via http://siteconfig.fivefilters.org/

### CODE REVIEW

**Comment by TheOneValen** [comment]
lowtechmagazine inner article is without comments

**Comment by j0k3r** [comment]
@fivefilters can you have a look at this one? Thanks :)

**Comment by fivefilters** [comment]
Thanks for these! 

If the issue is that reader comments at the end of the article are not kept, that tends to be the case in most of of the sites we process. 

I think comments are a tricky issue. In many cases they're not possible to preserve because they're hosted externally and rely on Javascript to be pulled in (e.g. Disqus), which makes them inaccessible to our tool. In cases where we can preserve them, I'm not sure we can assume that all users want the content with comments (some articles have hundreds if not thousands of comments). Might be nice to allow people to specify whether they want to preserve comments, and perhaps have the comments section handled separately, so that it can be attached to the article body if users want it. But I think offering this as an option without having a solution for sites which load comments in a way that's currently inaccessible to us could cause more confusion.

**Comment by TheOneValen** [comment]
I did not want to fetch the comments. I have honestly no idea how to test the extraction. I just used the tool at fivefilters.org and saw that the original filter config would have fetched the comments. Thats why I suggested the change.

**Pull request merged**
