### PR TITLE
Update zeit.de.txt

### PR DESCRIPTION
**Pull request by Hypfer**

### CODE REVIEW

**Comment by nicosomb** [comment]
Does it fix https://github.com/wallabag/wallabag/issues/4313 ?

**Comment by Hypfer** [comment]
Since I'm not using wallabag, I have no idea. I'd guess yes?

**Comment by nicosomb** [comment]
I tried your patch on my website and it works. Thank you!

**Comment by nicosomb** [comment]
@Hypfer does your patch still work? It's broken for me

**Comment by Hypfer** [comment]
Still works for me. What are you seeing exactly?

**Comment by nicosomb** [comment]
for this url `https://www.zeit.de/kultur/2020-04/social-distancing-hotel-adlon-coronavirus-tourismus-einsamkeit` I can't parse content. 

But with https://f43.me/feed/test and the updated zeit.de.txt, it works ...

**Comment by Hypfer** [comment]
Geoblocking, IPban or something like that maybe?

**Pull request merged**
