### PR TITLE
Add brainpickings.org

### PR DESCRIPTION
**Pull request by baxq**

### CODE REVIEW

**Comment by fivefilters** [comment]
Thanks for these, but is there a reason they're prefixed with a dot? We only use that for subdomain matches. The test URLs in your submission won't work with these config files unless you remove the dot at the beginning.

**Comment by fivefilters** [comment]
I should've said non-www subdomains. So example.org and www.example.org will match with example.org.txt.

**Comment by baxq** [comment]
Ah no, just me getting ahead of myself and not figuring out the syntax properly. I assumed the dot prefix would match any subdomains including www. Renamed it now, and also removed the one for The Atlantic as I realised there's already one for that, so I'll just figure out why that's not working properly and edit the existing one.

**Comment by fivefilters** [comment]
Thanks! Our subdomain matching is a little counter intuitive. :)

**Pull request merged**
