### PR TITLE
Updates 56 sites off ippen.media

### PR DESCRIPTION
**Pull request by HolgerAusB**
* reflect slight design-changes of the ippen.media engine
* now supporting author and date selectors
* better image handling
* should now better work with wallabag

I copied my template by script. So all 56 files are identical except for the `test_url` in the last line

### CODE REVIEW

**Comment by fivefilters** [comment]
Thanks @HolgerAusB! Do you think there's a suitable fragment string in these sites that we could use as a fingerprint, to have one site config file match all of them?

**Comment by HolgerAusB** [comment]
@fivefilters we already had this discussion about ippen.media. I am at work at the moment. Maybe I can look in it tonight, if that fingerprint, we found last year, is still valid.

**Comment by HolgerAusB** [comment]
reminder for me, to check this line in head
`<script>window.dataLayer = window.dataLayer||[];([{"de.ippen-digital.story.onlineId":`

**Comment by fivefilters** [comment]
Thanks @HolgerAusB, had forgotten about the earlier discussion. 👍

**Pull request merged**
