### PR TITLE
Backport site_config changes from wallabag v1

### PR DESCRIPTION
**Pull request by j0k3r**
I've managed to remove unwanted changes that were in your repo and not on wallabag. But I don't know if some files were removed from your repo and kept in the wallabag one.

Maybe you'll have an idea about that :)

Fix https://github.com/wallabag/wallabag/issues/1414

Happy New Year :tada:

### CODE REVIEW

**Comment by j0k3r** [comment]
@fivefilters did you have time to check that PR ?

**Comment by nicosomb** [comment]
Hello @fivefilters! 

Do you have any opinion on this PR please? We are waiting for that for our next release.

**Comment by fivefilters** [comment]
Thank you for this. I think many of these additions are in fact files that we removed from the repository because the sites in question stopped working, moved to a different domain, or changed significantly. For example

* alt1040.com redirects to a different domain
* alexduner.squarespace.com no longer works
* blog.jaysalvat.com no longer loads

My guess is that this PR contains a mixture of new stuff that made it to your repository and a bunch of old site config files that we deleted from our repository, because they were either dead sites or had changed significantly, invalidating all the XPath patterns for the site.

I will try to see if there's an easy way to figure out what's new and what's not so I can merge somehow. But not sure when that will be. If I accept it now, it will pull in the files we don't want in the repository.

**Comment by j0k3r** [comment]
I should have checked that on my side before sending all these files to you.
I've cleaned dead website, renamed website, etc ... and there are 44 files less.

**Comment by nicosomb** [comment]
:open_mouth:  :clap:

**Comment by fivefilters** [comment]
Thanks! Going through these today :)

**Comment by fivefilters** [comment]
Ok, so far the following are all sites that were in our repository and we deleted at some point. They don't appear to be updated in the pull request. I have more to go through, but if you could remove these from the pull request (I don't have privileges for that) I'll continue checking rest later. Thanks!

uzivatelsketestovani.cz
wmnf.org
quepasa.cl
sportschau.de
smokingapples.com
varingen.no
theappleblog.com
interest.co.nz
crazybutable.com
carpeaqua.com
dvice.com
vemedio.com
theeuropean-magazine.com
sportsillustrated.cnn.com
cedarrepublican.com
next-gen.biz
dukebasketballreport.com
on.net.mk
thecarton.net
pittnews.com
webpaper.nzz.ch

**Comment by j0k3r** [comment]
@fivefilters :white_check_mark:

**Comment by fivefilters** [comment]
Thanks! If you could remove these too, I think I can pull in the rest.

westhamtillidie.com
xfgjls.com
zingtrain.com
newsle.com
sebbo.net
gotomanager.com
laphamsquarterly.org
lovetv.com.bz
myfoxboston.com
datanami.com
technicallyjordan.tumblr.com
observer.com
edge.org
smartinvestor.de
csnbayarea.com
spectator.co.uk
sivers.org
etc.se
bostonreview.net
alexduner.squarespace.com
aachener-zeitung.de
winsupersite.com
thesiasat.com
thebrowser.com
narenji.ir
lovefm.com
danleech.com
community.servicenow.com
americascup.com

**Comment by j0k3r** [comment]
Down to 43 new files :)

**Comment by fivefilters** [comment]
Great! Merged! Many thanks. :)

**Comment by j0k3r** [comment]
w00t :rocket: 
Thanks !

**Pull request merged**
