### PR TITLE
Update site configs for ORF.at, derStandard.at and ZEIT.de

### PR DESCRIPTION
**Pull request by Lukas0907**
Hi,

I've updated (rewritten) site configs for the latest websites of ORF.at, derStandard.at and ZEIT.de. The latter also covers the ZEIT MAGAZIN which is available under the same domain but uses a different layout (see also the according test URLs).

Cheers,

Lukas

### CODE REVIEW

**Comment by Lukas0907** [comment]
Hi,

I wonder if there's anything that is blocking this PR.

Cheers,

Lukas

**Comment by fivefilters** [comment]
Lukas, sorry, nothing blocking it other than lack of email notification reaching our inbox alerting us to it. :) Thank you again!

**Comment by Lukas0907** [comment]
Thanks a lot! Is there also a way to file pull requests against full-text-rss itself?

**Comment by fivefilters** [comment]
Hi Lukas,

Allowing pull requests for Full-Text RSS itself is a little trickier as we sell the software, so getting code contributions from users is more complicated. What we've done in the past is accept certain code contributions and included them in both the public version (usually one version behind the one we sell) and the version we sell, so user-contributed improvements become available for all.

**Pull request merged**
