### PR TITLE
Create m.dw.com.txt

### PR DESCRIPTION
**Pull request by Marmo**

### CODE REVIEW

**Comment by j0k3r** [comment]
You are only targeting the mobile version, is there a reason?

**Comment by Marmo** [comment]
Hm ... would `.dw.com.txt` also apply for `m.dw.com`?
Then changing the body xpath to
```
# mobile version m.dw.com
body: //div[@class='article__intro'] | //div[@itemprop='articleBody']
# desktop version www.dw.com
body: //p[contains(concat(' ',normalize-space(@class),' '), ' intro ')] | //div[contains(concat(' ',normalize-space(@class),' '), ' longText ')]
```
and adding
```
test_url: https://www.dw.com/de/wie-sieht-die-zukunft-von-fridays-for-future-aus/a-50436506
```
would make it work for both the desktop and the mobile site.

**Comment by Marmo** [comment]
Ah  well I just saw in the Readme, that `.dw.com.txt` will **not** apply for `www.dw.com`, so that means we need both `m.dw.com.txt` *and* `dw.com.txt`? Is there a possibility to just create one file and making the second one a symlink to the first?

**Comment by j0k3r** [comment]
Sorry we can't create a symlink

**Comment by Marmo** [comment]
ok i guess i'll close this one and create two new fresh pull reuests for the two files needed.

**Pull request closed without merging**
