### PR TITLE
Create brentozar.com.txt

### PR DESCRIPTION
**Pull request by andre-faria**

### CODE REVIEW

**Comment by fivefilters** [comment]
Thank you, but I'm not sure what you're trying to extract here.

Isn't the main body element in the test_url matched by the following selector:

    //div[contains(concat(' ',normalize-space(@class),' '),' post_content ')]

Are you trying to extract something other than the post body?

**Comment by andre-faria** [comment]
Hello just be patient with me, newbie here.

I'm trying to extract just the body element, I just pointed my mouse to close as possible for the article as the image below shows.

image

**Comment by andre-faria** [comment]
```
# Generated by FiveFilters.org's web-based selection tool
# Place this file inside your site_config/custom/ folder
# Source: http://siteconfig.fivefilters.org/grab.php?url=https%3A%2F%2Fwww.brentozar.com%2Farchive%2F2018%2F06%2Fcpu-cores-or-memory-offline-the-problem-with-standard-edition-vms%2F

body: //div[contains(concat(' ',normalize-space(@class),' '),' post_content ')]
test_url: https://www.brentozar.com/archive/2018/06/cpu-cores-or-memory-offline-the-problem-with-standard-edition-vms/
```

**Comment by fivefilters** [comment]
Ah I see, thanks! Can be a bit tricky finding the right element. I got a confused because I couldn't see where the long XPath came from, but makes sense now.

When you're using that tool, after you select an element (when the border turns red) you can try using the left and right arrow keys to change the selected element. Using the left key will try to select the parent element. The right key will try to select the next inner element (up to a point). Works better than the mouse in some cases when there are lots of tightly nested elements.

**Comment by andre-faria** [comment]
> Ah I see, thanks! Can be a bit tricky finding the right element. I got confused because I couldn't see where the long XPath came from, but makes sense now.
> 
> When you're using that tool, after you select an element (when the border turns red) you can try using the left and right arrow keys to change the selected element. Using the left key will try to select the parent element. The right key will try to select the next inner element (up to a point). Works better than the mouse in some cases when there are lots of tightly nested elements.

This is a great tip, For sure it will help me a lot, thank you very much!

**Pull request merged**
