### PR TITLE
Create dice.com.txt

### PR DESCRIPTION
**Pull request by digicommons**

### CODE REVIEW

**Comment by HolgerAusB** [comment]
@digicommons same question here. Why stripping featured-image?

In this case, you did not specify a body selector and Fulltext-RSS (FTR) as well as wallabag finds it themself. Both originally don't contain that image.

But FTR is somewhat special at this point. If the found body does not contain any image, it tries to get an image from the html-header, here from `<meta property="og:image"...` and puts that in front of the article. You can prevent this by setting a line into your site config file:
`insert_detected_image: no`

**Comment by digicommons** [comment]
Thanks for the tip! Since `insert_detected_image` is not included in the [FTR site patterns docs](https://help.fivefilters.org/full-text-rss/site-patterns.html#pattern-format), I didn't know about this pattern. Is there an overview of configs, I might've overlooked?

I didn't specify a body selector since FTR/Wallabag did a good job with extracting the desired sections. For stripping the lead/featured-image, please see my answer [here](https://github.com/fivefilters/ftr-site-config/pull/1250#issuecomment-1817658529).

**Comment by HolgerAusB** [comment]
> Is there an overview of configs, I might've overlooked?

unfortunately not. I've learned a lot by reading the issues here and in wallbag/wallbag and in the [Fivefilters-Forum](https://forum.fivefilters.org/)

**Comment by digicommons** [comment]
Inspired by the lack of an overview, I just ran grep on the site configs and extracted what looked like config directives. Maybe having such a list could be useful?

[ftr-site-config-directives](https://github.com/digicommons/ftr-site-config-directives)

**Pull request merged**
