### PR TITLE
Update lalibre.be and add rtbf.be

### PR DESCRIPTION
**Pull request by kujiu**
Actually, the filter lalibre.be.txt doesn't work anymore. A commit fix that.

The other commit adds the rtbf.be website (an official media in Belgium).

### CODE REVIEW

**Comment by HolgerAusB** [comment]
Thank you @kujiu for this.

For lalibre I added some extra tweeks. Stripped author-box (was scrambled in FTR), stripped footer, which has some unnecessary leftovers in wallabag.

rtbf works fine in FTR and with wallabagger, but not with wallabag UI, due to JavaScript. I will add some changes here later today

**Comment by HolgerAusB** [comment]
my fault, didn't copied rtbf.be.txt to my wallabag, works fine with wallabagg UI, too. But I will try to add a fix for the wrong indentation in wallabag (caused by same class names used on rtbf and wallabag)

**Comment by HolgerAusB** [comment]
done: https://github.com/fivefilters/ftr-site-config/pull/1332

**Comment by kujiu** [comment]
Thank you!

**Pull request merged**
