### PR TITLE
enterprisersproject.com.txt

### PR DESCRIPTION
**Pull request by shtrom**
I added a `next_page_link`, as this is needed for this site, but it still doesn't work on https://f43.me/feed/test at the moment.

Creating this PR so we can work through fixing it.

Signed-off-by: Olivier Mehani <shtrom@ssji.net>

### CODE REVIEW

**Comment by j0k3r** [comment]
I've updated the file with better stripping.
Let me know what do you think and I'll merge it

**Comment by shtrom** [comment]
This looks good. It still grabs the title and header from the second page, but I'm not sure how to work around that.

**Comment by shtrom** [comment]
Yup, LGTM (tested in f43.me and Wallabag), save for the duplicated summary.

I tried adding ```strip_id_or_class: field-items```, but that killed the entire content.

**Comment by j0k3r** [comment]
Yeah it's hard to remove title & header from the second page as it's fetched like it's a new page

**Pull request merged**
