### PR TITLE
global: strip all class attributes by default

### PR DESCRIPTION
**Pull request by Kdecherf**
Fixes https://github.com/wallabag/wallabag/issues/3134

### CODE REVIEW

**Comment by Kdecherf** [comment]
This change may break the other options that would use the stripped attributes as selectors if `strip_attr` is not executed last.

**Comment by Kdecherf** [comment]
Hello there, I updated my PR to prevent any breaking change.

I'm proposing a new keyword for site configs named `post_strip_attr`. It would let processors strip any attributes after any content processing. Our issue on wallabag is that some classes from fetched content are rendered using the stylesheets of our web client, this keyword would let graby strip these classes without actually breaking rules which rely on them.

**Comment by Kdecherf** [comment]
@fivefilters are you ok with this proposal?

**Comment by fivefilters** [comment]
Hi, I'm not against the proposal, and can definitely see the benefit, but I do wonder if there are some users who use these extraction tools and then do their own additional cleanup or more granular extraction relying on such class attributes. To my mind, if these attributes are being removed only to help with how an article gets presented in Wallabag (avoiding CSS conflicts), then they ought to be removed by Wallabag after article extraction, not by the article extractor. But I confess this is a bit of a grey area - there's definitely stuff in site config files to improve presentation.

I'm going to merge this as our Full-Text RSS code doesn't understand this new directive at the moment, so won't affect things on our side. But I think if we added support for this we'd want users to request it explicitly in the request, something like `&post_processing_cleanup=1` which would then apply any `post_` directives.

**Comment by j0k3r** [comment]
Yeah I agree.
Thanks for merging!

**Comment by Kdecherf** [comment]
@fivefilters noted, thanks for your feedback and for merging :)

**Pull request merged**
