### PR TITLE
Update arstechnica.com.txt

### PR DESCRIPTION
**Pull request by sztanpet**
The exact same as arstechnica.co.uk.txt because it works perfectly

### CODE REVIEW

**Comment by sztanpet** [comment]
Oh, and this fixes the problem of arstechnica.com articles are not downloaded past the first page

**Comment by fivefilters** [comment]
Thank you for this. Is there a reason why the other rules in the site config files have been removed? E.g. native_ad_clue? If it's just the single_page_link that you've tested, let us know and we'll just amend that line.

**Comment by sztanpet** [comment]
I literally just copied the UK sites and tested with both single and multi-page articles in wallabag, it worked perfectly.

**Comment by fivefilters** [comment]
Thank you! :+1:

**Comment by sztanpet** [comment]
This doesnt seem to work, I tested my own changes but the one that was applied is not the same.
Only a single page is downloaded, never all the pages this way (the original problem).

**Comment by sztanpet** [comment]
Oh, the version installed by the latest wallabag update didn't contain this change yet, nevermind :(

**Pull request merged**
